{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Logs Chart",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(level) (count_over_time({component=\"jwt-pizza-service\"} [$__auto]))"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "requestLatency_milliseconds_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "pizzaLatency_milliseconds_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memoryUsage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpuUsage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "targets": [
    { "expr": "pizzasSold_total", "legendFormat": "__auto" },
    { "expr": "pizzaFails_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "targets": [
    { "expr": "activeUsers_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "revenue_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "targets": [
    { "expr": "postRequests_total", "legendFormat": "__auto" },
    { "expr": "deleteRequests_total", "legendFormat": "__auto" },
    { "expr": "putRequests_total", "legendFormat": "__auto" },
    { "expr": "getRequests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 37 },
   "targets": [
    { "expr": "successfulAuth_total", "legendFormat": "__auto" },
    { "expr": "failedAuth_total", "legendFormat": "__auto" }
   ]
  }
 ]
}